version: '3.4'

services:
  notionbot:
    image: notionbot
    network_mode: host
    build:
      context: .
      dockerfile: ./Dockerfile
      network: host
    environment:
      NODE_ENV: production
      TZ: America/New_York
      NOTION_KEY: ${NOTION_KEY}
      NOTION_TASKS_DATABASE: ${NOTION_TASKS_DATABASE}
      NOTION_BILLS_DATABASE: ${NOTION_BILLS_DATABASE}
      NOTION_BOOKS_DATABASE: ${NOTION_BOOKS_DATABASE}